### ISSUE TITLE
opening costumers menu lags

### ISSUE THREAD

**Issue by manups4e** [ESX-Org/esx_realestateagentjob#12]
Whenever one of my agents wants to open the costumers list menu.. the server starts lagging..after 5 minutes where the server is stuck the menu opens..

**Comment by ElPumpo** [comment]
https://github.com/ESX-Org/esx_menu_list/commit/922f0c17a7109430321ee512c341ca5442107233 should have improved this, a bit

**Comment by manups4e** [comment]
Thx :)

Il giorno Mer 31 Ott 2018, 16:07 Samuel <notifications@github.com> ha
scritto:

**Comment by ElPumpo** [comment]
Issue fixed?

**Comment by manups4e** [comment]
Don't know yet.. I'll try this evening


Il giorno Mer 31 Ott 2018, 16:53 Samuel <notifications@github.com> ha
scritto:

**Comment by manups4e** [comment]
no the issue is not fixed... in my test server alone it takes 1 second of lag to open the menu list..
i think the main problem is how the count it's handled in server/main.lua

**Comment by manups4e** [comment]
[MySQL] [Slow Query Warning] [esx_addonaccount] [184664ms] UPDATE addon_account_data SET money = 36017 WHERE account_name = 'society_realestateagent'

this happens only with this script
