### ISSUE TITLE
Propeties menu issue

### ISSUE THREAD

**Issue by driftonez** [ESX-Org/esx_realestateagentjob#17]
i can open the properties menu but i can do any actions or close the menu afterwards, resulting in needing a client restart.

**Comment by BrandsPickled** [comment]
He means you cannot do cant do any actions, Like you access it but you click the buttons they dont do nothing and that trying to press backspace / esc nothing happens

**Comment by ev1lnz** [comment]
i also cant do anything i get stuck i have to either f8 quit or die then revive i get stuck with the properties menu open getting this error when ever i press esc or backspace

https://gyazo.com/fe353b140c68365afb68d60ca8204cff

**Comment by dwiprizzy** [comment]
anyone  know to fix it  this problem
